### ISSUE TITLE
Segfault when sending a lot of new peer packets

### ISSUE THREAD

**Issue by alnf** [alnf/toxcore#27]
<irungentoo> new groupchats are nowhere near being ready for master
:D 
We shouldn't have give people access. Anyway, irun said:
<irungentoo> I just spam new peer packets and you segfault

**Comment by alnf** [comment]
So, basically it doesn't check peer pk and so on.

**Comment by JFreegman** [comment]
I made a simple fix by limiting the number of peers who can join a group to 1 per second. This turns exploding the group into being mildly annoying, and moderators can deal with it this way. However the fix opens a new possibility of preventing anyone from joining the chat by spamming it with join requests. In order to deal with that we'd probably have to do some sort of IP filtering.

**Comment by alnf** [comment]
What is bad is that you can get peer list while joining and spam every peer even without announcements, so there should be some ip filtering, but I'm not sure on which level (tox or not).

**Comment by alnf** [comment]
I think we can close this and if necessary create another issue with more appropriate name aka "prevent peer join spam with ip filtering", cause we no longer have segfault, rite?

**Comment by JFreegman** [comment]
People can no longer crash groups by spamming peer joins, but there are still other related problems that perhaps moderation will take care of. that's a somewhat different issue for the future though.
