### ISSUE TITLE
remove "ENCRYPTION_KEY" in "(namely, in nodes closest to chatid ENCRYPTION_KEY)." on https://github.com/alnf/toxcore/wiki/General-GC-rules

### ISSUE THREAD

**Issue by aaannndddyyy** [alnf/toxcore#35]
lookups are done with public Ed25519 key, not encryption key

**Comment by alnf** [comment]
Removed

**Comment by aaannndddyyy** [comment]
Another perfectly valid point and the invalid tag just speaks for @JFreegman's state of mind.

**Comment by alnf** [comment]
The main point was not about the wrong or not issue, but about creating a lot of issues to change any tiny article or comma, especially considering that we are rewriting wiki more or less frequently. If you want to improve grammar in several places it is more convenient to create "Improve wiki grammar issue".

I would refrain from making personal statements.

**Comment by aaannndddyyy** [comment]
I do not refrain from it, as it is a fact.
Also, it is better to open a ticket per issue, so it is easier to check which one was resolved already and which not.

**Comment by alnf** [comment]
> I do not refrain from it, as it is a fact.
> @aaannndddyyy What do you mean by that?

**Comment by aaannndddyyy** [comment]
@alnf His state of mind. Closing valid tickets, tagging them as invalid, and leaving inaccuracies in the wiki without proper reason.

**Comment by alnf** [comment]
@aaannndddyyy Saying smth about one's state of mind is very offensive, especially when you are not a doctor. You was already told that we don't have time to keep the wiki up to date with the current code, and you cannot demand it from us, cause we do it entirely volunteerely. Also we told you that wiki (at least at the current stage) is more for our own needs, to keep track of not even implemented or fail ideas sometimes. You should have asked us about the consistency of wiki and the current code/ideas before making the assuptions and blaming us. Also, I edit wiki mostly, so @JFreegman is not repsonsible for leaving outdated information at all.

We are working on groupchats because of our free will, so we consider your behaviour very demanding for no reason. If you don't like current implementation for any reason and you consider main developer being in the particular state of mind you can start your own implementation, that is the power of opensource.

@JFreegman is the main developer of groupchats now, therefore I don't see the point of insulting the main developer. 

We consider your way of interaction unproductive, especially spamming with issues for chaning tiny grammar mistakes, even after you were told that it is not very comfortable for us. While the style of creating issues might be arguable, statement about someone's mind is inappropriate, therefore, unfortunately, I have to block you.
